src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use App\Service\UploaderHelper;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProductRepository::class)
 */
class Product
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $metaTitle;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $metaDescription;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $price = 0.00;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="products")
     */
    private $category;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="integer")
     */
    private $count;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $imageFilename;

    /**
     * @ORM\OneToMany(targetEntity=ProductReference::class, mappedBy="product")
     */
    private $productReferences;

    public function __construct()
    {
        $this->productReferences = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getMetaTitle(): ?string
    {
        return $this->metaTitle;
    }

    public function setMetaTitle(?string $metaTitle): self
    {
        $this->metaTitle = $metaTitle;

        return $this;
    }

    public function getMetaDescription(): ?string
    {
        return $this->metaDescription;
    }

    public function setMetaDescription(?string $metaDescription): self
    {
        $this->metaDescription = $metaDescription;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(string $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getCount(): ?int
    {
        return $this->count;
    }

    public function setCount(int $count): self
    {
        $this->count = $count;

        return $this;
    }

    public function getImageFilename(): ?string
    {
        return $this->imageFilename;
    }

    public function setImageFilename(?string $imageFilename): self
    {
        $this->imageFilename = $imageFilename;

        return $this;
    }

    public function getImagePath(): ?string
    {
        return UploaderHelper::PRODUCT_IMAGE.'/'.$this->getImageFilename();
    }

    /**
     * @return Collection|ProductReference[]
     */
    public function getProductReferences(): Collection
    {
        return $this->productReferences;
    }
}

src/Controller/ProductController.php
<?php


namespace App\Controller;


use Symfony\Component\Routing\Annotation\Route;

class ProductController extends BaseController
{

    /**
     * @Route("/p/{slug}/{id}", name="app_product_index")
     */
    public function product()
    {
        return $this->render('shop/product/index.html.twig');
    }
}

templates/shop/product/bestsellers.html.twig
<div class="col-10 col-md-6 col-lg-3 product">
    <div class="product-image">
        <img class="img-fluid" src="{{ asset('img/products/1.jpg') }}" alt="">
    </div>
    <div class="product-info">
        <p class="product-title">
            Bluza damska szara
        </p>
        <div class="product-price-basket">
            <p class="price m-0">
                <b>189.00 zł</b>
            </p>
            <span class="add-to-basket">
                <i class="fas fa-shopping-basket"></i>
            </span>
        </div>
    </div>
</div>
<div class="col-12 col-md-6 col-lg-3 product">
    <div class="product-image">
        <img class="img-fluid" src="{{ asset('img/products/2.jpg') }}" alt="">
    </div>
    <div class="product-info">
        <p class="product-title">
            Bluza damska czerwona
        </p>
        <div class="product-price-basket">
            <p class="price m-0">
                <b>189.00 zł</b>
            </p>
            <span class="add-to-basket">
                <i class="fas fa-shopping-basket"></i>
            </span>
        </div>
    </div>
</div>
<div class="col-12 col-md-6 col-lg-3 product">
    <div class="product-image">
        <img class="img-fluid" src="{{ asset('img/products/3.jpg') }}" alt="">
    </div>
    <div class="product-info">
        <p class="product-title">
            Bluza damska pomarańczowa z super długą nazwą produktu
        </p>
        <div class="product-price-basket">
            <p class="price m-0">
                <b>189.00 zł</b>
            </p>
            <span class="add-to-basket">
                <i class="fas fa-shopping-basket"></i>
            </span>
        </div>
    </div>
</div>
<div class="col-12 col-md-6 col-lg-3 product">
    <div class="product-image">
        <img class="img-fluid" src="{{ asset('img/products/4.jpg') }}" alt="">
    </div>
    <div class="product-info">
        <p class="product-title">
            Bluza damska różowa
        </p>
        <div class="product-price-basket">
            <p class="price m-0">
                <b>189.00 zł</b>
            </p>
            <span class="add-to-basket">
                <i class="fas fa-shopping-basket"></i>
            </span>
        </div>
    </div>
</div>

templates/shop/product/index.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    {% include 'parts/side_nav.html.twig' %}
    <div class="col-12 col-lg-9">
        <div class="row">
            <div class="col-12">
                <h1 class="underline-title">Bluza damska</h1>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="row">
                    <div class="col-12 col-md-6">
                        <div class="product-image-container border">
                            <img class="max-width-height" src="http://localhost/smartshop/img/products/1.jpg" alt="">
                        </div>
                        <div class="row">
                            <div class="col-3 mr-0 pr-0">
                                <div class="product-image-gallery border">
                                    <img class="max-width-height" src="http://localhost/smartshop/img/products/1.jpg" alt="">
                                </div>
                            </div>
                            <div class="col-3 mr-0">
                                <div class="product-image-gallery border">
                                    <img class="max-width-height" src="http://localhost/smartshop/img/products/1.jpg" alt="">
                                </div>
                            </div>
                            <div class="col-3 mr-0">
                                <div class="product-image-gallery border">
                                    <img class="max-width-height" src="http://localhost/smartshop/img/products/1.jpg" alt="">
                                </div>
                            </div>
                            <div class="col-3 mr-0">
                                <div class="product-image-gallery border">
                                    <img class="max-width-height" src="http://localhost/smartshop/img/products/1.jpg" alt="">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-md-6">
                        <table class="product-availability">
                            <tr>
                                <td>Dostępność:</td>
                                <td>w magazynie</td>
                            </tr>
                            <tr>
                                <td>Wysyłka w:</td>
                                <td>24h</td>
                            </tr>
                            <tr>
                                <td>Dostawa:</td>
                                <td>od 6,99 zł</td>
                            </tr>
                            <tr>
                                <td>Kod produktu:</td>
                                <td>PDL-221S</td>
                            </tr>
                        </table>
                        <div class="product-price">129,00 zł</div>

                        <div class="row">
                            <div class="col-8 mt-3">
                                <div class="form-group">
                                    <label for="exampleSelect1">Wybierz rozmiar</label>
                                    <select class="form-control" id="exampleSelect1">
                                        <option>XS</option>
                                        <option>S</option>
                                        <option>M</option>
                                        <option>L</option>
                                        <option>XL</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12">
                                <div class="form-group product-count">
                                    <label for="product-count-input">Ilość</label>
                                    <span class="product-minus-count">-</span>
                                    <input type="number" value="1" id="product-count-input">
                                    <span class="product-plus-count">+</span>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12">
                                <button type="button" class="btn btn-primary">Do koszyka</button>
                            </div>
                        </div>



                    </div>
                </div>
                <div class="row">
                    <div class="col-12 mt-4">
                        <p class="text-justify">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ultrices dignissim orci.
                            Ut lacinia ex metus, sed cursus magna imperdiet ac. Ut pellentesque quis metus accumsan lobortis.
                            Integer placerat tellus quis ipsum tristique, nec auctor nisl facilisis. Maecenas mollis hendrerit consequat.
                            Fusce ut tortor sed magna dapibus consequat. Donec dapibus ante nec magna aliquam luctus.
                            Maecenas consectetur, sapien eget auctor egestas, tellus velit euismod leo, at vehicula justo lacus vitae ipsum.
                            Curabitur ultrices dolor non risus aliquam euismod. Aenean id ipsum leo. Maecenas consectetur enim ut nunc molestie, et tincidunt mauris varius.
                            Nullam sollicitudin dictum risus, ac ornare tellus laoreet tincidunt. Nam auctor diam sit amet lacus varius consectetur.
                            Quisque in euismod ipsum, nec ornare urna. Proin velit odio, ultricies sit amet dapibus id, interdum a lacus.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/shop/product/new_products.html.twig
{% for product in products %}
    <div class="col-12 col-md-6 col-lg-3 product">
        <div class="product-image">
            <img class="img-fluid" src="{{ product.imagePath|imagine_filter('squared_thumbnail_small') }}"
                 alt="">
        </div>
        <div class="product-info">
            <p class="product-title">
                {{ product.title }}
            </p>
            <div class="product__price-listing">
                <p class="price m-0">
                    <b>{{ product.price }} zł</b>
                </p>
                <span class="add-to-basket">
                    <i class="fas fa-shopping-basket"></i>
                </span>
            </div>
        </div>
    </div>
{% endfor %}